USED_IN = {
    # EUROSTAT
    "unemployment":            ["resumo", "emprego", "europa"],
    "ipi_manufacturing":       ["resumo", "industria", "europa"],
    "ipi_total":               ["industria", "europa"],
    "hicp":                    ["resumo", "europa"],
    "gdp_quarterly":           ["macro", "europa"],
    "gdp_per_capita_eur":      ["fosso", "europa"],
    "gov_debt_pct_gdp":        ["macro", "europa"],
    "gov_deficit_pct_gdp":     ["macro"],
    "employment_rate":         ["emprego", "europa", "fosso"],
    "consumer_confidence":     ["emprego"],
    "cci":                     ["emprego"],
    "construction_output":     ["industria"],
    "ipi_food_beverage":       ["industria"],
    "ipi_textiles":            ["industria"],
    "ipi_nonmetallic":         ["industria"],
    "ipi_electronics":         ["industria"],
    "ipi_wood_paper":          ["industria"],
    "manufacturing":           ["resumo", "industria", "europa"],
    "total_industry":          ["industria", "europa"],
    "metals":                  ["industria"],
    "chemicals_pharma":        ["industria"],
    "transport_eq":            ["industria"],
    "inflation":               ["resumo", "europa"],
    # INE
    "ipi_seasonal_cae":        ["industria", "resumo"],
    "ipi_seasonal_cae_24":     ["industria"],
    "ipi_seasonal_cae_20":     ["industria"],
    "ipi_seasonal_cae_29":     ["industria"],
    "ipi_seasonal_cae_10":     ["industria"],
    "ipi_seasonal_cae_TOT":    ["industria", "resumo"],
    "ipi_seasonal_cae_25":     ["industria"],
    "ipi_seasonal_cae_28":     ["industria"],
    "ipi_yoy_cae":             ["industria"],
    "wages_industry_cae":      ["emprego"],
    "conf_manufacturing":      ["emprego"],
    "emp_industry_cae":        ["emprego"],
    "hicp_yoy":                ["resumo"],
    "exports_monthly":         ["macro"],
    # BPORTUGAL
    "euribor_1m":              ["macro"],
    "euribor_3m":              ["macro", "resumo"],
    "euribor_6m":              ["macro"],
    "euribor_12m":             ["macro"],
    "spread_pt_de":            ["macro"],
    "credit_housing":          ["macro"],
    "credit_consumer":         ["macro"],
    "deposits":                ["macro"],
    "eur_usd":                 ["macro"],
    "pt_10y":                  ["macro"],
    "de_10y":                  ["macro"],
    # WORLDBANK
    "birth_rate":              ["fosso"],
    "rnd_pct_gdp":             ["fosso", "europa"],
    "gdp_per_capita":          ["macro"],
    "gdp_growth":              ["macro"],
    "fdi_inflows_pct_gdp":     ["europa"],
    "female_labor_participation": ["emprego"],
    # OECD
    "cli":                     ["emprego"],
    "order_books":             ["industria"],
    "production":              ["industria"],
    "selling_prices":          ["industria"],
    "employment":              ["emprego"],
    "unemp_m":                 ["emprego", "resumo"],
    # FRED
    "brent_oil":               ["energia"],
    "natural_gas":             ["energia"],
    "coal":                    ["energia"],
    "copper":                  ["industria", "energia"],
    "aluminum":                ["industria", "energia"],
    "wheat":                   ["energia"],
    "corn":                    ["energia"],
    "coffee":                  ["energia"],
    # DGEG / REN / ERSE
    "pct_renewable_real":      ["energia"],
    "electricity_price_mibel": ["energia", "resumo"],
    "electricity_consumption": ["energia"],
    "electricity_production_renewable": ["energia"],
    "electricity_production_total": ["energia"],
    "renewable_share_electricity": ["energia"],
    "renewable_share_total":   ["energia"],
    "energy_dependence":       ["energia"],
    "energy_intensity":        ["energia"],
}

# FRED indicator -> FRED series code
FRED_SERIES = {
    "brent_oil":   "DCOILBRENTEU",
    "natural_gas": "DHHNGSP",
    "coal":        "PCOALAUUSDM",
    "copper":      "PCOPPUSDM",
    "aluminum":    "PALUMUSDM",
    "wheat":       "PWHEAMTUSDM",
    "corn":        "PMAIZMTUSDM",
    "coffee":      "PCOFFOTUSDM",
    "eur_usd":     "DEXUSEU",
}

# WorldBank indicator -> World Bank indicator code
WB_CODES = {
    "birth_rate":              "SP.DYN.CBRT.IN",
    "rnd_pct_gdp":             "GB.XPD.RSDV.GD.ZS",
    "gdp_per_capita":          "NY.GDP.PCAP.CD",
    "gdp_growth":              "NY.GDP.MKTP.KD.ZG",
    "fdi_inflows_pct_gdp":     "BX.KLT.DINV.WD.GD.ZS",
    "female_labor_participation": "SL.TLF.CACT.FE.ZS",
    "gdp_per_capita_ppp":      "NY.GDP.PCAP.PP.CD",
    "employment_to_population":"SL.EMP.TOTL.SP.ZS",
}

SOURCE_META = {
    "EUROSTAT": {"label": "Eurostat",                            "url": "https://ec.europa.eu/eurostat/databrowser/"},
    "INE":      {"label": "INE — Instituto Nacional de Estatística", "url": "https://www.ine.pt/xportal/xmain?xpid=INE&xpgid=ine_BD_tema"},
    "FRED":     {"label": "FRED — Federal Reserve Bank of St. Louis","url": "https://fred.stlouisfed.org"},
    "WORLDBANK":{"label": "World Bank",                          "url": "https://data.worldbank.org/"},
    "BPORTUGAL":{"label": "Banco de Portugal",                   "url": "https://www.bportugal.pt/estatisticas/dados"},
    "OECD":     {"label": "OCDE",                                "url": "https://stats.oecd.org/"},
    "REN":      {"label": "REN — Redes Energéticas Nacionais",   "url": "https://datahub.ren.pt/app/pt/producao/"},
    "ERSE":     {"label": "ERSE — Entidade Reguladora dos Serviços Energéticos", "url": "https://www.erse.pt/"},
    "DGEG":     {"label": "DGEG — Direção-Geral de Energia e Geologia", "url": "https://www.dgeg.gov.pt/media/"},
}

# Human-readable unit overrides for raw DB codes
UNIT_OVERRIDES = {
    "PT_LF_SUB": "%",
    "PT_IX":     "índice",
    "EUR/MWh":   "€/MWh",
    "PC_LF":     "%",
    "PC_ACT":    "%",
    # Index base year variants
    "index_2021=100":  "Índice (2021=100)",
    "Index 2021=100":  "Índice (2021=100)",
    "index 2021=100":  "Índice (2021=100)",
    "index_2015=100":  "Índice (2015=100)",
    "Index 2015=100":  "Índice (2015=100)",
}
